apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"app.kiegroup.org/v2","kind":"KieApp","metadata":{"name":"rhpam-trial"},"spec":{"environment":"rhpam-trial"}}]'
    capabilities: Seamless Upgrades
    categories: Integration & Delivery
    certified: "true"
    containerImage: registry.redhat.io/rhpam-7/rhpam-rhel8-operator:7.5.1
    createdAt: "2019-10-31 13:29:39"
    description: Business Automation Operator for deployment and management of RHPAM/RHDM
      environments.
    repository: https://github.com/kiegroup/kie-cloud-operator
    support: Red Hat, Inc.
    tectonic-visibility: ocs
  labels:
    operator-businessautomation: "true"
  name: businessautomation-operator.1.2.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: A project prescription running an RHPAM/RHDM environment.
      displayName: KieApp
      kind: KieApp
      name: kieapps.app.kiegroup.org
      resources:
      - kind: DeploymentConfig
        name: ""
        version: apps.openshift.io/v1
      - kind: StatefulSet
        name: ""
        version: apps/v1
      - kind: Role
        name: ""
        version: rbac.authorization.k8s.io/v1
      - kind: RoleBinding
        name: ""
        version: rbac.authorization.k8s.io/v1
      - kind: Route
        name: ""
        version: route.openshift.io/v1
      - kind: BuildConfig
        name: ""
        version: build.openshift.io/v1
      - kind: ImageStream
        name: ""
        version: image.openshift.io/v1
      - kind: Secret
        name: ""
        version: v1
      - kind: PersistentVolumeClaim
        name: ""
        version: v1
      - kind: ServiceAccount
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      specDescriptors:
      - description: Set true to enable automatic micro version product upgrades,
          it is disabled by default.
        displayName: Enable Upgrades
        path: upgrades.enabled
        value: false
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Set true to enable automatic minor product version upgrades,
          it is disabled by default. Requires spec.upgrades.enabled to be true.
        displayName: Include minor version upgrades
        path: upgrades.minor
        value: false
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Environment deployed.
        displayName: Environment
        path: environment
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: Product version installed.
        displayName: Version
        path: version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      statusDescriptors:
      - description: Deployments for the KieApp environment.
        displayName: Deployments
        path: deployments
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      - description: Current phase.
        displayName: Status
        path: phase
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: The address for accessing Business Central, if it is deployed.
        displayName: Business/Decision Central URL
        path: consoleHost
        x-descriptors:
        - urn:alm:descriptor:org.w3:link
      version: v2
  description: Business Automation Operator for deployment and management of RHPAM/RHDM
    environments.
  displayName: Business Automation
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMH0uY2xzLTJ7ZmlsbDojYzIxYTAwfS5jbHMtM3tmaWxsOiNmZmZ9LmNscy00e2ZpbGw6I2VhZWFlYX0uY2xzLTV7ZmlsbDojYjdiN2I3fS5jbHMtNntmaWxsOiNjZGNkY2R9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkxvZ288L3RpdGxlPjxnIGlkPSJMYXllcl8xIiBkYXRhLW5hbWU9IkxheWVyIDEiPjxjaXJjbGUgY2xhc3M9ImNscy0xIiBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiIHRyYW5zZm9ybT0icm90YXRlKC00NSA1MCA1MCkiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik04NS4zNiAxNC42NGE1MCA1MCAwIDAgMS03MC43MiA3MC43MnoiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik02NS43NiAzNC4yOEwxNS42IDQzLjE1djEuMTNhLjM0LjM0IDAgMCAwIC4zLjM0YzEuNDcuMTcgNy45MyAyLjExIDggMjMuNDlhLjQ2LjQ2IDAgMCAwIC4zNS40NGwyLjU5LjU3cy0xLjIxLTI1LjU0IDguNzctMjcuMDYgMTEuMiAyNy4yNyAxMS4zMyAzMS4xYS41NC41NCAwIDAgMCAuNDMuNTFsMy41MS43OHMuMDYtMzQuNTQgMTQuOTItMzYuODJ2LTMuMzV6Ii8+PHBhdGggY2xhc3M9ImNscy00IiBkPSJNNjUuMzUgMjcuNTZMMTYuMTggMzguNDJhLjc1Ljc1IDAgMCAwLS41OS43M3Y0bDUwLjE3LTguODd2LTYuNzZhMS42OCAxLjY4IDAgMCAwLS40MS4wNHoiLz48cGF0aCBjbGFzcz0iY2xzLTUiIGQ9Ik0zNS42MSA0Mi4wNWMtNC42MS43LTYuODMgNi41NC03Ljg5IDEyLjYxbDEzLjY1LTEuMzNjMC0uMTcuMDktLjM0LjEzLS41MXMuMTQtLjUzLjIxLS44bC4yLS42OHEuMTItLjQuMjUtLjhsLjItLjYyYy4xMi0uMzYuMjUtLjcxLjM5LTEuMDZsLjEyLS4zMmMtMS42NC00LjE3LTMuOTgtNi45OS03LjI2LTYuNDl6TTgyLjIzIDMxLjE5bC0xNi0zLjYyYTEuOSAxLjkgMCAwIDAtLjQyIDB2Ni43NmwxNy4wNiAyLjgzdi01LjIzYS43Ni43NiAwIDAgMC0uNjQtLjc0ek01My40MyA1My42MmwxOC40MS0xLjEzYzIuMS02LjA1IDUuNTEtMTEuNzUgMTEtMTIuOGwtMTctMi4wOGMtNi42OCAxLjEyLTEwLjM2IDguMjktMTIuNDEgMTYuMDF6Ii8+PHBhdGggY2xhc3M9ImNscy02IiBkPSJNNDEuNzEgNTJsLjEzLS40NS0uMTMuNDZ6TTQxLjkxIDUxLjM0bC0uMDYuMjIuMDctLjIzek0yNy43MiA1NC42NmE2OC4yNiA2OC4yNiAwIDAgMC0uOTMgMTJ2Mi40MkwzOSA2Ni4xYTEuMDYgMS4wNiAwIDAgMCAuODEtMSA1OC43MiA1OC43MiAwIDAgMSAxLjY5LTEyLjI2YzAgLjE2LS4wOS4zMy0uMTMuNDl6TTY1Ljc4IDM0LjI4bC4wMSAzLjM0IDE3LjAzIDIuMDd2LTIuNThsLTE3LjA0LTIuODN6TTUwLjg3IDc0LjQ0TDY4IDY4LjY4YS45Mi45MiAwIDAgMCAuNjMtLjc5IDcyLjQ2IDcyLjQ2IDAgMCAxIDMuMTgtMTUuNGwtMTguMzggMS4xM2E5MC45MSA5MC45MSAwIDAgMC0yLjU2IDIwLjgyek01My40MyA1My42MnoiLz48L2c+PC9zdmc+
    mediatype: image/svg+xml
  install:
    spec:
      deployments:
      - name: business-automation-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: business-automation-operator
          strategy:
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 1
            type: RollingUpdate
          template:
            metadata:
              labels:
                name: business-automation-operator
            spec:
              containers:
              - command:
                - kie-cloud-operator
                env:
                - name: OPERATOR_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['name']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: OPERATOR_UI
                  value: "true"
                - name: DEBUG
                  value: "false"
                image: registry.redhat.io/rhpam-7/rhpam-rhel8-operator:7.5.1
                imagePullPolicy: Always
                name: business-automation-operator
                resources: {}
              serviceAccountName: business-automation-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          - apps
          - apps.openshift.io
          - rbac.authorization.k8s.io
          - route.openshift.io
          - build.openshift.io
          - image.openshift.io
          - app.kiegroup.org
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - operators.coreos.com
          resources:
          - clusterserviceversions
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - business-automation-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        serviceAccountName: business-automation-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - kieapp
  - pam
  - decision
  - kie
  - cloud
  - bpm
  - process
  - automation
  - operator
  labels:
    alm-owner-businessautomation: businessautomation-operator
    operated-by: businessautomation-operator.1.2.1
  links:
  - name: Product Page
    url: https://access.redhat.com/products/red-hat-process-automation-manager
  - name: Documentation
    url: https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.5/#category-deploying-red-hat-process-automation-manager-on-openshift
  maintainers:
  - email: bsig-cloud@redhat.com
    name: Red Hat, Inc.
  maturity: stable
  provider:
    name: Red Hat, Inc.
  replaces: businessautomation-operator.1.2.0
  selector:
    matchLabels:
      alm-owner-businessautomation: businessautomation-operator
      operated-by: businessautomation-operator.1.2.1
  version: 1.2.1
