apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusteragents.appdynamics.com
spec:
  group: appdynamics.com
  names:
    kind: Clusteragent
    listKind: ClusteragentList
    plural: clusteragents
    singular: clusteragent
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
