---
# Source: tigera-operator/templates/tigera-operator/00-namespace-tigera-operator.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: tigera-operator
  annotations:
    openshift.io/node-selector: ""
  labels:
    name: tigera-operator
    openshift.io/run-level: "0"


