apiVersion: v1
baseDomain: redhat.ren
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 2
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: cmri
networking:
  clusterNetworks:
  - cidr: 10.254.0.0/16
    hostPrefix: 24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"registry.redhat.ren:5443": {"auth": "ZHVtbXk6ZHVtbXk=","email": "noemail@localhost"},"registry.ppa.redhat.ren:5443": {"auth": "ZHVtbXk6ZHVtbXk=","email": "noemail@localhost"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzXtqRUNHarvrkrZrz5yiV5NzedhEKp+tv6nzLcuPm/SEooQsrV3rgqYdJRAFWLksNbKgdQ1dh+/McQJgB0OFcecuaKVA9u9kIvoQmjrI/rTrWJHbt0edRzGLCeK/6FIigoW+NWJL2KJuSw7IqWs13nFl5TGykEHdmLJGpU+IprQpyYZE4P/GGAGM8h9hLwqU66vfbAJJZiWDWA3CArHKNbZQ5QkbCwmHKuBZGXTbou/oJirKHUJsl8GKdiepPfoZFQhEXn1ZlXSWwoNtgJbL56YrZdqUIZE2WppoEvZqjsbxtZsOsO7bVK+ULeEV5wLwcA4mHMxMmuGDFTOSmeezB root@helper
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHl3gXNPiPMBT6jZ7c/TYLWyCDNurnfxXfc9zcvKriiQCBFtAF24k8N+kBSSTVVG9VKKkc2BZAkEmeaJerbNhNsn16iq8LsgyWryb5UF8la4YcX4yesBjunJTPXe8y4CtEOgplDJ4uPIrKkBrBneD5JqUx+9a1R57qqGz20fEKIBUiZEEuXevexNKSGEcZe/k3s00OyX6S3Yk1UIy9k+m4+LFbendixYEjCbfaIXzdgJAg65v74+Eb2itEQ80acuyGFKfYsZxNRQzCpx6J5yv2s0VaXhoe21IS6fCD0q3u+yOAPJbu/qv2dNEDukMFXKgZrboS9Bho72VoBYLtQOrt wangzheng@localhost
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIDszCCApugAwIBAgIJAO6p/FX9zuJ/MA0GCSqGSIb3DQEBCwUAMHAxCzAJBgNV
  BAYTAkNOMQswCQYDVQQIDAJHRDELMAkGA1UEBwwCU1oxGDAWBgNVBAoMD0dsb2Jh
  bCBTZWN1cml0eTEWMBQGA1UECwwNSVQgRGVwYXJ0bWVudDEVMBMGA1UEAwwMKi5y
  ZWRoYXQucmVuMB4XDTIwMDcwMTE0MzkwNVoXDTMwMDYyOTE0MzkwNVowcDELMAkG
  A1UEBhMCQ04xCzAJBgNVBAgMAkdEMQswCQYDVQQHDAJTWjEYMBYGA1UECgwPR2xv
  YmFsIFNlY3VyaXR5MRYwFAYDVQQLDA1JVCBEZXBhcnRtZW50MRUwEwYDVQQDDAwq
  LnJlZGhhdC5yZW4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDguVbY
  K99ZUe00WpL5kE6+EnGRhFKAt5UlzvpMbIHEJxn1325bVBDzNQubQrbZrskj0IzX
  pqJ3NNgxENgCo9D7F1o9RUBAXAGIiWha+MYujHVT6AGns5OmWO1eDwvbDMhGOUjN
  +NDiyxGRvhds/zqIuVoZZwBlR1ubLL7ogG/8h+6KuHus/GwBI+p+hZ/Azg8tgMJP
  3LNW86zGXBdwdwkkNrbBf1unxYd8Hqef3cVHHn61I0UR9Dc3itxCyXn6yZWR16s9
  pnhSnFIC1aqjks3VzaSHqQ5KTy4tXVo1mNIHxN9o5iYClUm1T3CrpscnBrxthP+N
  KprR8c3ZDMfwosqxAgMBAAGjUDBOMB0GA1UdDgQWBBRYohHD1YHoH11IbdZ4XsrM
  THBNADAfBgNVHSMEGDAWgBRYohHD1YHoH11IbdZ4XsrMTHBNADAMBgNVHRMEBTAD
  AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBdVFSSQpShz56aqtkp+1JM7xQbJSYeL2XE
  GwkNJbm3Ag7CzMyROmo0ZvgoVTWjjQwSD0Z76cuUvpJdG3Zd2Pyu2BoNO6cgpLiE
  sj3XTIdrEoss80Ja9TdGgP1nIbDaB3JcviB6r0wic8pLuw7oHLL9riQa/+mO2tOE
  qkbciSIQ60OS7xaqi0jP0VtkhqeCOQ1iq6InADPf6mvCYf6a6UvIkdyWz3oq4z1d
  hunIqTbwzPR08lUU9Huz8QgIn/I0BnfycBzp435FsTf1ZD2BEF7iEi/JyVruA67b
  ClQ/aTXiKrv8ZNzbvOw7hQEr3MaEL4Z8/Cd2K7c7lmaBshrCx2tP
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - registry.redhat.ren:5443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.redhat.ren:5443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
