#! validate-crd: deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
#! parse-kind: ClusterServiceVersion
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: elasticsearch-operator.4.2.11-201912100122
  namespace: placeholder
  annotations:
    categories: "OpenShift Optional, Logging & Tracing"
    capabilities: "Seamless Upgrades"
    certified: "false"
    description: |-
      The Elasticsearch Operator for OKD provides a means for configuring and managing an Elasticsearch cluster for tracing and cluster logging.
      ## Prerequisites and Requirements
      ### Elasticsearch Operator Namespace
      The Elasticsearch Operator must be deployed to the global operator group namespace
      ### Memory Considerations
      Elasticsearch is a memory intensive application.  The initial
      set of OKD nodes may not be large enough to support the Elasticsearch cluster.  Additional OKD nodes must be added
      to the OKD cluster if you desire to run with the recommended (or better) memory. Each ES node can operate with a
      lower memory setting though this is not recommended for production deployments.
    containerImage: registry.redhat.io/openshift4/ose-elasticsearch-operator@sha256:9248df62b82116a40523e9ac38a876e856147ac57cf9f43dece4858bd034c14f
    createdAt: 2019-02-20T08:00:00Z
    support: AOS Cluster Logging, Jaeger
    olm.skipRange: ">=4.1.0 <4.2.11-201912100122"
    alm-examples: |-
        [
            {
                "apiVersion": "logging.openshift.io/v1",
                "kind": "Elasticsearch",
                "metadata": {
                  "name": "elasticsearch"
                },
                "spec": {
                  "managementState": "Managed",
                  "nodeSpec": {
                    "image": "registry.redhat.io/openshift4/ose-logging-elasticsearch5@sha256:8a48e74a649a53f0a27e6365b87d295241415e6b975dffa912a63cd459cd823a",
                    "resources": {
                      "limits": {
                        "memory": "1Gi"
                      },
                      "requests": {
                        "memory": "512Mi"
                      }
                    }
                  },
                  "redundancyPolicy": "SingleRedundancy",
                  "nodes": [
                    {
                        "nodeCount": 1,
                        "roles": ["client","data","master"]
                    }
                  ]
                }
            }
        ]
spec:
  version: 4.2.11-201912100122
  displayName: Elasticsearch Operator

  description: |
    The Elasticsearch Operator for OKD provides a means for configuring and managing an Elasticsearch cluster for use in tracing and cluster logging.
    This operator only supports OKD Cluster Logging and Jaeger.  It is tightly coupled to each and is not currently capable of
    being used as a general purpose manager of Elasticsearch clusters running on OKD.

    It is recommended this operator be deployed to the **openshift-operators** namespace to properly support the Cluster Logging and Jaeger use cases.

    Once installed, the operator provides the following features:
    * **Create/Destroy**: Deploy an Elasticsearch cluster to the same namespace in which the Elasticsearch custom resource is created.

  keywords: ['elasticsearch', 'jaeger']

  maintainers:
  - name: Red Hat, AOS Logging
    email: aos-logging@redhat.com

  provider:
    name: Red Hat, Inc

  links:
  - name: Elastic
    url: https://www.elastic.co/
  - name: Elasticsearch Operator
    url: https://github.com/openshift/elasticsearch-operator
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: false
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: elasticsearch-operator
        rules:
        - apiGroups:
          - logging.openshift.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - pods/exec
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - serviceaccounts
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - "*"
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - prometheusrules
          - servicemonitors
          verbs:
          - "*"
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          verbs:
          - "*"
        - nonResourceURLs:
          - "/metrics"
          verbs:
          - get
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
      deployments:
      - name: elasticsearch-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: elasticsearch-operator
          template:
            metadata:
              labels:
                name: elasticsearch-operator
            spec:
              serviceAccountName: elasticsearch-operator
              containers:
                - name: elasticsearch-operator
                  image: registry.redhat.io/openshift4/ose-elasticsearch-operator@sha256:9248df62b82116a40523e9ac38a876e856147ac57cf9f43dece4858bd034c14f
                  imagePullPolicy: IfNotPresent
                  command:
                  - elasticsearch-operator
                  ports:
                  - containerPort: 60000
                    name: metrics
                  env:
                    - name: WATCH_NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.annotations['olm.targetNamespaces']
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: OPERATOR_NAME
                      value: "elasticsearch-operator"
                    - name: PROXY_IMAGE
                      value: "registry.redhat.io/openshift4/ose-oauth-proxy@sha256:86e282e319f97bab460e8afd3dc3033448942f3418f7d6259d4c2ddae0a65923"
                    - name: ELASTICSEARCH_IMAGE
                      value: "registry.redhat.io/openshift4/ose-logging-elasticsearch5@sha256:8a48e74a649a53f0a27e6365b87d295241415e6b975dffa912a63cd459cd823a"
  customresourcedefinitions:
    owned:
    - name: elasticsearches.logging.openshift.io
      version: v1
      kind: Elasticsearch
      displayName: Elasticsearch
      description: An Elasticsearch cluster instance
      resources:
      - kind: Deployment
        version: v1
      - kind: StatefulSet
        version: v1
      - kind: ReplicaSet
        version: v1
      - kind: Pod
        version: v1
      - kind: ConfigMap
        version: v1
      - kind: Service
        version: v1
      - kind: Route
        version: v1
      specDescriptors:
      - description: Limits describes the minimum/maximum amount of compute resources required/allowed
        displayName: Resource Requirements
        path: nodeSpec.resources
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:resourceRequirements'
      statusDescriptors:
      - description: The current Status of the Elasticsearch Cluster
        displayName: Status
        path: cluster.status
        x-descriptors:
          - 'urn:alm:descriptor:io.kubernetes.phase'
      - description: The number of Active Primary Shards for the Elasticsearch Cluster
        displayName: Active Primary Shards
        path: cluster.activePrimShards
        x-descriptors:
          - 'urn:alm:descriptor:text'
      - description: The number of Active Shards for the Elasticsearch Cluster
        displayName: Active Shards
        path: cluster.activeShards
        x-descriptors:
          - 'urn:alm:descriptor:text'
      - description: The number of Initializing Shards for the Elasticsearch Cluster
        displayName: Initializing Shards
        path: cluster.initializingShards
        x-descriptors:
          - 'urn:alm:descriptor:text'
      - description: The number of Data Nodes for the Elasticsearch Cluster
        displayName: Number of Data Nodes
        path: cluster.numDataNodes
        x-descriptors:
          - 'urn:alm:descriptor:text'
      - description: The number of Nodes for the Elasticsearch Cluster
        displayName: Number of Nodes
        path: cluster.numNodes
        x-descriptors:
          - 'urn:alm:descriptor:text'
      - description: The number of Relocating Shards for the Elasticsearch Cluster
        displayName: Relocating Shards
        path: cluster.relocatingShards
        x-descriptors:
          - 'urn:alm:descriptor:text'
      - description: The number of Unassigned Shards for the Elasticsearch Cluster
        displayName: Unassigned Shards
        path: cluster.unassignedShards
        x-descriptors:
          - 'urn:alm:descriptor:text'
      - description: The status for each of the Elasticsearch pods with the Client role
        displayName: Elasticsearch Client Status
        path: pods.client
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podStatuses'
      - description: The status for each of the Elasticsearch pods with the Data role
        displayName: Elasticsearch Data Status
        path: pods.data
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podStatuses'
      - description: The status for each of the Elasticsearch pods with the Master role
        displayName: Elasticsearch Master Status
        path: pods.master
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podStatuses'
