apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: newrelics.apm.newrelic.com
spec:
  group: apm.newrelic.com
  names:
    kind: NewRelic
    listKind: NewRelicList
    plural: newrelics
    singular: newrelic
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
